name: CI

on: [push]

jobs:
  dogfood:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typescript-version: ['3.2.4', 'latest']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: Use Typescript ${{ matrix.typescript-version }}
      run: |
        npm install typescript@${{ matrix.typescript-version}}
    - name: Run checks
      run: |
        ./dist/index.js tsc tsconfig.json
        ./dist/index.js tslint tsconfig.json
        ./dist/index.js eslint .
  report-typescript-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: Run and report checks
      run: |
        ./dist/index.js tsc tsconfig.json --repo ${{ github.repository }}
        ./dist/index.js tslint tsconfig.json --repo ${{ github.repository }}
        ./dist/index.js eslint tsconfig.json --repo ${{ github.repository }}
      env:
        GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
        GITHUB_APP_INSTALLATION_ID: ${{ secrets.GITHUB_APP_INSTALLATION_ID }}
        GITHUB_APP_CLIENT_ID: ${{ secrets.GITHUB_APP_CLIENT_ID }}
        GITHUB_APP_CLIENT_SECRET: ${{ secrets.GITHUB_APP_CLIENT_SECRET }}
